name: iOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Archive
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v3

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_16.0.app

    - name: Install XcodeGen
      run: brew install xcodegen

    - name: Generate Xcode Project
      run: xcodegen generate

    - name: Build and Archive
      run: |
        xcodebuild clean archive -project nuts2pin.xcodeproj \
                                 -scheme nuts2pin \
                                 -configuration Release \
                                 -archivePath "build/nuts2pin.xcarchive" \
                                 CODE_SIGNING_ALLOWED=NO \
                                 CODE_SIGN_IDENTITY=""

    - name: Export IPA
      run: |
        xcodebuild -exportArchive -archivePath "build/nuts2pin.xcarchive" \
                                  -exportPath "build/" \
                                  -exportOptionsPlist exportOptions.plist

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: nuts2pin.ipa
        path: build/nuts2pin.ipa 